spring.application.name=week06-lab01

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url = jdbc:h2:mem:testdb

spring.jpa.defer-datasource-initialization=true
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

jwt.secret=2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b
jwt.expiration-access=3600000
jwt.expiration-refresh=3600000

ADMIN_NAME=Cameron Walker
ADMIN_EMAIL=cameron@example.com
ADMIN_NOTIFICATION_EMAIL=alerts@example.com
